### ISSUE TITLE
Is the 2.0 version compatible with redis-py 3.x ?

### ISSUE THREAD

**Issue by mikhail-mmlc** [RediSearch/redisearch-py#110]
[redis-py](https://github.com/andymccurdy/redis-py) 3.x introduces a number of[ backwards incompatible changes](https://github.com/andymccurdy/redis-py#upgrading-from-redis-py-2x-to-30). 
Is the redisearch-py 2.0 compatible with the redis-py 3.x?

**Comment by gkorland** [comment]
It should but we never test it, thanks for the issue

**Comment by gkorland** [comment]
The current version depends on 3.5
