### ISSUE TITLE
How to configure the redisearch in flask?

### ISSUE THREAD

**Issue by cnvsuresh** [RediSearch/redisearch-py#111]
I've used the example which is available in the readme file.
I've missed the configuration setup. 
Because of no configuration, it's showing the below error:

> redis.exceptions.ResponseError
redis.exceptions.ResponseError: unknown command `FT.SEARCH`, with args beginning with: `myIndex`, `search engine`, `LIMIT`, `0`, `10`,

Can you please help me on this?

**Comment by gkorland** [comment]
How did you start the server?

**Comment by cnvsuresh** [comment]
I've installed the redisearch-py by using pip in flask. And then added the example in code. 

```
from flask_restful import Resource
from redisearch import Client, TextField, IndexDefinition, Query


class RedisClass(Resource):
    @staticmethod
    def post():
        # Creating a client with a given index name
        client = Client("myIndex")

        # IndexDefinition is available for RediSearch 2.0+
        definition = IndexDefinition(prefix=['doc:', 'article:'])

        # Creating the index definition and schema
        client.create_index((TextField("title", weight=5.0), TextField("body")), definition=definition)

        # Indexing a document for RediSearch 2.0+
        client.redis.hset('doc:1',
                          mapping={
                              'title': 'RediSearch',
                              'body': 'Redisearch impements a search engine on top of redis'
                          })

        # Indexing a document for RediSearch 1.x
        client.add_document(
            "doc:2",
            title="RediSearch",
            body="Redisearch implements a search engine on top of redis",
        )
        return True

```

After that i'm trying to call the post method from API level.

**Comment by abrookins** [comment]
Usually that error means that the Redis server you're trying to use does not have the redisearch module installed. @cnvsuresh How did you start the Redis server, or where is it running?

**Comment by cnvsureshg** [comment]
I've added the Redis Caching by using the Flask-Caching in the project. There only I've added Redis configuration to connect. But related to redisearch I didn't mention any configuration to connect. 

How can I provide Redisearch configuration?

**Comment by cnvsuresh** [comment]
Can I use this library with enterprise Redis without using the docker image which is provided from this library?

**Comment by ashtul** [comment]
Yes.

**Comment by ashtul** [comment]
Yes.
Personally, for testing, I start a local instance and run `REDIS_PORT=6379 python test/test.py`

**Comment by abrookins** [comment]
@cnvsuresh You can, yes. If you're using Redis Enterprise Cloud, then these docs can help you turn on RediSearch: https://docs.redislabs.com/latest/modules/modules-quickstart/

You should be able to use the Docker image in the way you mentioned earlier for local testing: start it with the command you gave and connect to it with the code you used, so if that's not working, your Flask code may be connecting to the wrong Redis instance -- not the one you started with our RediSearch Docker image.

**Comment by cnvsuresh** [comment]
@ashtul Internally it's using Docker with your suggestion. If my statement wrong can you suggest to me how to provide my custom URL/Enterprise URL in code?

**Comment by cnvsuresh** [comment]
Thanks, @abrookins Now all set. I'm able to use the enterprise account instead of docker. Thanks for the help. 

In the future, if is there any case to store the array of objects in redisearch. let us know it'll really help.
