### ISSUE TITLE
Client.drop_index uses the deprecated FT.DROP command, destroying all indexed Hashes

### ISSUE THREAD

**Issue by abrookins** [RediSearch/redisearch-py#114]
FT.DROP is deprecated and by default deletes the indexed Hashes. Calling `Client.drop_index` thus deletes the indexed hashes.

This library should use FT.DROPINDEX for its drop command and expose the DD option to control whether or not to delete Hashes, with 'False' being the default. This way, dropping an index will not destroy the Hashes by default.

**Comment by abrookins** [comment]
@emmanuelkeller What do you think about this? I'm worried that someone will try to drop a 2.0 index and accidentally destroy data.

**Comment by emmanuelkeller** [comment]
@abrookins  You are absolutely right. This is currently done in this PR. Waiting for merge

https://github.com/RediSearch/redisearch-py/pull/108

**Comment by abrookins** [comment]
Fixed by #108.
