### ISSUE TITLE
Docs are out of date or contain errors

### ISSUE THREAD

**Issue by rankam** [RediSearch/redisearch-py#137]
- There is no type `NumericalField`, it is `NumericField`
- Client doesn't accept username as an parameter
`client = Client("my-index", username="user", password="my-password")`
- The following example that you show doesn't work - you can't set a Python datetime object in Redis

```
import datetime

from redisearch import Client

START_TIME = datetime.datetime.now()

client = Client("my-index")

client.redis.set("start-time", START_TIME)
```
- This example is missing a colon
```
try:
    client.info()
except ResponseError
    # Index does not exist. We need to create it!
    client.create_index(SCHEMA, definition=definition)

**Comment by chayim** [comment]
Thanks @rankam! I issued a [pull request](https://github.com/RediSearch/redisearch-py/pull/138) to update the documents.
