### ISSUE TITLE
Autocomplete wildcard

### ISSUE THREAD

**Issue by AdiFahmi** [RediSearch/redisearch-py#23]
Hi, is it possible for the autocomplete to behave like mysql _like_ wildcard (* + query + *) operator?

Example:

ac = AutoCompleter('ac')

ac.add_suggestions(Suggestion('this contains space', 5.0))

suggs = ac.get_suggestions('thi', fuzzy = True)
returns ['this contains space']

suggs = ac.get_suggestions('contains', fuzzy = True)
returns nothing

suggs = ac.get_suggestions('spa', fuzzy = True)
returns nothing

Thanks.

**Comment by gkorland** [comment]
It's a RediSearch feature https://github.com/RediSearch/RediSearch/issues/348
