### ISSUE TITLE
password support

### ISSUE THREAD

**Issue by kerneljake** [RediSearch/redisearch-py#36]
redisearch-py should support database passwords like redis-py does.

Optimally, it should also support the same connection pool and ssl settings that can be passed to the redis-py Redis object.

**Comment by itamarhaber** [comment]
Hello @kerneljake,

The redisearch-py client supports the provisioning of an arbitrary connection object (pooled or otherwise) via the `conn` initialization argument, per the class' `__init__` signature:

```python
def __init__(self, index_name, host='localhost', port=6379, conn=None)
```

🙂

**Comment by kerneljake** [comment]
✅
