### ISSUE TITLE
Github repo out of sync with Pypi?

### ISSUE THREAD

**Issue by vulcan25** [RediSearch/redisearch-py#39]
I've installed this and confirmed the version:
```
$ docker run -it python:3.7.3-slim-stretch /bin/sh
# pip install redisearch
Collecting redisearch
  Downloading https://files.pythonhosted.org/packages/8b/86/27afb885aac7849f221f72153ecc46f6b2084ad476e459f1c818aa932ddc/redisearch-0.7.1.tar.gz
[SNIP]
Successfully installed hiredis-1.0.0 redis-3.3.8 redisearch-0.7.1 rmtest-0.7.0
# pip freeze                 
hiredis==1.0.0
redis==3.3.8
redisearch==0.7.1
rmtest==0.7.0
```
This matches the version string (`0.7.1`) in the repo's [setup.py](https://github.com/RediSearch/redisearch-py/blob/master/setup.py#L8) at the time of writing.  However on checking the contents of the `site-packages/redisearch` directory:
```
# ls /usr/local/lib/python3.7/site-packages/redisearch
__init__.py  __pycache__  _util.py  auto_complete.py  client.py
document.py  query.py	result.py
```
... a number of files are missing, particularly:
```
aggregation.py
querystring.py
reducers.py
```
Comparing hashes of the files in repo vs pypi, shows of what's present only `client.py` differs:
```
REPO: (client.py) = 0e0f1f41de306c663b9627154da57afe
PYPI: (client.py) = 67a827573fbfb6772997a64f52278812 
```
Can this be fixed, or is there a reason that the latest code hasn't been pushed to Pypi?

**Comment by cheeseandcereal** [comment]
Release 0.8.0 has gone out. This should be resolved due to that
