### ISSUE TITLE
phonetic field option

### ISSUE THREAD

**Issue by victusfate** [RediSearch/redisearch-py#48]
Greetings.

I'm reviewing RediSearch and wanted to know how I'd pass Phonetic text field options to the python client.

I looked at the [source code](https://github.com/RediSearch/redisearch-py/blob/master/redisearch/client.py) and didn't see a way to pass it (was hoping it'd be similar to weight).

something like
client.create_index((TextField('title', weight=5.0), TextField('body', phonetic='dm:en')),)

The text field option is defined here https://oss.redislabs.com/redisearch/Commands.html

Any help would be appreciated. Worst case I can make redis-cli system calls but this client looks great for my usage otherwise.

**Comment by leibale** [comment]
`phonetic_matcher` was added in v0.9.0, and can be used like that:
```python
TextField('body', phonetic_matcher='dm:en')
```
