### ISSUE TITLE
res.docs not returning all elements in query

### ISSUE THREAD

**Issue by kivo360** [RediSearch/redisearch-py#63]
I'm running a `Query()` object and I'm able to find 46 items when using the `res.total` command. However, when using `res.docs`, I'm only able to have 10 of those documents returned to me.

Why is this? I don't have any unreasonable limits on the query for that to happen.

**Comment by gkorland** [comment]
@kivo360 can you please add a simple recreation or code snippet?

**Comment by kivo360** [comment]
Hi @gkorland I figured it out. It was a pagination issue. I simply increased the pagination to pull the relevant records.
