### ISSUE TITLE
NameError: name 'IndexDefinition' is not defined 

### ISSUE THREAD

**Issue by loveJasmine** [RediSearch/redisearch-py#80]
Traceback (most recent call last):
  File "demoRediSearch.py", line 19, in <module>
    definition = IndexDefinition(prefix=['doc:', 'article:'])
NameError: name 'IndexDefinition' is not defined

**Comment by loveJasmine** [comment]
use pip install -e .

**Comment by loveJasmine** [comment]
still exist

**Comment by gkorland** [comment]
what is "demoRediSearch.py"?
