### ISSUE TITLE
bug in the latest version.

### ISSUE THREAD

**Issue by loveJasmine** [RediSearch/redisearch-py#81]
ub16_prj/bumblebee % python demoRediSearch.py
Traceback (most recent call last):
  File "demoRediSearch.py", line 25, in <module>
    from redisearch import Client, TextField
  File "/Users/yuanke/ghSrc/redisearch-py/redisearch/__init__.py", line 73, in <module>
    from .client import Client, NumericField, TextField, GeoField, TagField, IndexDefinition
  File "/Users/yuanke/ghSrc/redisearch-py/redisearch/client.py", line 116
    def __init__(self, async=False, prefix=[], filter=None, language_field=None, language=None, score_field=None, score=1.0, payload_field=None):
                       ^
SyntaxError: invalid syntax

**Comment by rafie** [comment]
Hello @loveJasmine,
Could you please quote `demoRediSearch.py` in your report (gist is ok)?
It would also help to have some information on your environment:
- Which OS are you running?
- Which Python version are you using?
- Are you running in a virtual environment?
- How did you install rediserch-py?

Thanks

**Comment by gzyunke** [comment]
![image](https://user-images.githubusercontent.com/4013363/90867590-33307700-e3c8-11ea-936b-bdaf28ac7ef8.png)
async is a keyword
